version: '3.5'
services:
  bender-web-client:
    image: dreem/bender-web-client
    container_name: bender-web-client
    ports:
      - "${WEB_CLIENT_PORT:-3000}:8000"
    networks:
      - bender-network
    environment:
      - API_URL=http:\/\/localhost:${API_PORT:-8000}
  bender-database:
    image: "postgres:9.6"
    container_name: bender-database
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    networks:
      - bender-network
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    volumes:
      - ${DATABASE_PATH}:/var/lib/postgresql/data
  bender-api:
    image: dreem/bender-api
    container_name: bender-api
    depends_on:
      - bender-database
    ports:
      - "${API_PORT:-8000}:8000"
    networks:
      - bender-network
    environment:
      - DJANGO_SETTINGS_MODULE=bender_service.settings.development
    command: bash /run_packaged.sh ${USERNAME} ${EMAIL} ${PASSWORD} ${DATABASE_PORT:-5432}

networks:
  bender-network:
    driver: bridge